---
title: An ML Pipeline in R
author: ~
date: '2018-09-26'
slug: an-ml-pipeline-in-r
categories: [Fixed Camera Surveillance, Machine Learning Pipeline]
tags: [R,scheduler]
draft: yes
header:
  caption: ''
  image: ''
  preview: yes
---

# Introduction

What is a machine learning pipeline? An oil pipeline transports petroleum from one location to another. A machine learning pipeline is similar only in the sense that we put stuff into one end and it emerges at the other end. There are also some refineries along the way, that transform the product as it passes through. In the example that follows, we put one or more video files into the inlet, and the same number of videos emerge at the outlet, each having been transformed. 

Imagine how the pipeline will be used. We stuff 'PATH/to/Video/Files/' into the inlet. The pipeline needs to do two things, represented below as a simple schedule:

| id | task                  | status |
|---:|:----------------------|:-------|
|  1 | list video files      | Pending|
|  2 | build recipe for each | Pending|


Let's say the recipe we wish to apply to each video looks something like this:


| id | task                  | status |
|---:|:----------------------|:-------|
|  1 | extract images        | Pending|
|  2 | make HoGs             | Pending|
|  3 | cluster the HoGs      | Pending|


3. After building the recipes, the schedule looks like this:


| id | task                    | status |
|---:|:------------------------|:-------|
|  1 | list video files        | Done   |
|  2 | build recipe for each   | Done   |
|  3 | extract images   VIDEO1 | Pending|
|  4 | make HoGs        VIDEO1 | Pending|
|  5 | cluster the HoGs VIDEO1 | Pending|
|  6 | extract images   VIDEO2 | Pending|
|  7 | make HoGs        VIDEO2 | Pending|
|  8 | cluster the HoGs VIDEO2 | Pending|
| ...| ...                     | Pending|


To keep track of the transformations and transportation the pipeline will accomplish, we will need some kind of scheduling mechanism that can do the following things:

* Add a task
* Perform the next task
* Update the status of the current task
* Show the current schedule
* Save the current schedule to a text file
* Read a schedule from a text file

In order to *Perform the next task*, the mechanism must know where to find the detailed steps for each task it will encounter.
